# Generated by Django 4.2.18 on 2025-02-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cmp_name',
            field=models.CharField(default='Default Company', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='pqty',
            field=models.IntegerField(default=0),
        ),
    ]
