# Generated by Django 4.2.18 on 2025-02-17 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_cmp_name_product_pqty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pid',
        ),
    ]
