# Generated by Django 4.2.18 on 2025-03-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_profilepic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profilepic',
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
